'use strict';
const baseline={stores:2000,velocity:50,price:20,promo:25,stock:97,competitor:19};
const samples={base:{stores:1900,velocity:46,price:21,promo:18,stock:93,competitor:19},distribution:{stores:1600,velocity:51,price:20,promo:25,stock:97,competitor:19},recovery:{stores:1950,velocity:52,price:20,promo:25,stock:98,competitor:19}};
function calculate(d){const b=baseline,weeks=8,prior=b.stores*b.velocity*weeks*b.price,units=d.stores*d.velocity*weeks,sales=units*d.price;return{prior,units,sales,change:sales/prior-1,storeEffect:(d.stores-b.stores)*b.velocity*weeks*b.price,velocityEffect:d.stores*(d.velocity-b.velocity)*weeks*b.price,priceEffect:units*(d.price-b.price)};}
if(typeof module!=='undefined')module.exports={calculate,samples,baseline};
if(typeof document!=='undefined'){
const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n),pct=n=>(n>0?'+':'')+(n*100).toFixed(1)+'%',compact=n=>'$'+(n/1e6).toFixed(2)+'M';
let current='base',selected='sales';
function metrics(d,c){return{sales:{label:'Dollar sales',value:compact(c.sales),delta:c.change,prior:compact(c.prior),note:'Sales = units × realized price. All values are synthetic.',next:'Separate volume from price before diagnosing demand.'},units:{label:'Units sold',value:c.units.toLocaleString(),delta:c.units/800000-1,prior:'800,000',note:'Units = average selling stores × weekly velocity × 8 weeks.',next:'Investigate store coverage and demand within stores separately.'},price:{label:'Realized price / unit',value:money(d.price),delta:d.price/20-1,prior:'$20',watch:d.price>20,note:'Price increases add dollars per unit but may weaken demand. One consistent pack size is assumed.',next:'Compare price per pound, promotion timing, and matched SKUs before concluding shoppers traded down.'},stores:{label:'Avg. selling stores',value:d.stores.toLocaleString(),delta:d.stores/2000-1,prior:'2,000',note:'Average stores recording sales across the 8-week window. This is not weighted ACV distribution.',next:'Check authorization, delistings, and zero-sales stores. A stockout can look like distribution loss.'},velocity:{label:'Units / store / week',value:String(d.velocity),delta:d.velocity/50-1,prior:'50',note:'Average volume per selling store per week. Assortment and store mix can change this average.',next:'Compare like-for-like stores and SKUs, controlling for stock availability, price, and promotions.'}};}
function render(key){current=key;const d=samples[key],c=calculate(d),m=metrics(d,c);function card(id){const v=m[id],cls=v.watch?'yellow':v.delta<0?'red':v.delta>0?'green':'yellow';return `<button class="metric" data-metric="${id}" aria-pressed="${selected===id}"><span class="label">${v.label}</span><strong>${v.value}</strong><span class="change ${cls}">${v.delta<0?'↓':v.delta>0?'↑':'→'} ${pct(v.delta)}${v.watch?' · Watch':''}</span><small>Prior year: ${v.prior}</small></button>`;}
$('tree').innerHTML=`<div class="tree-row">${card('sales')}</div><div class="branches"><div class="unit-branch"><div class="tree-row">${card('units')}</div><div class="tree-row">${card('stores')}${card('velocity')}</div></div><div class="price-branch">${card('price')}</div></div>`;
// Bottom row decomposes units; price is the separate branch above.
$('tree').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{selected=b.dataset.metric;render(current);}));
$('detail').innerHTML=`<strong>${m[selected].label}: inspect the evidence</strong><p>${m[selected].note}</p><p><strong>Next check:</strong> ${m[selected].next}</p>`;
const declining=c.sales<c.prior,dist=Math.abs(c.storeEffect)>Math.abs(c.velocityEffect);
$('answer-title').textContent=declining?(dist?'Fewer selling stores explain most of the gap.':'Lower velocity is the largest arithmetic drag.'):'The recovery scenario reverses the sales decline.';
$('answer').textContent=`Sales ${declining?'fell':'rose'} ${pct(c.change)} (${money(c.sales-c.prior)}) versus the prior-year sample. Store coverage ${d.stores<2000?'fell':'rose'} ${pct(d.stores/2000-1)}, while units per store per week ${d.velocity<50?'fell':'rose'} ${pct(d.velocity/50-1)}. ${d.price>20?'A higher realized price partially offset the unit decline. Lower promotion support and weaker availability are plausible contributors, not proven causes.':'Price was unchanged. Validate the store and SKU mix before treating the pattern as a causal result.'}`;
$('bridge').innerHTML=[['Store coverage',c.storeEffect],['Velocity',c.velocityEffect],['Price',c.priceEffect]].map(([label,v])=>`<div class="${v<0?'red':v>0?'green':'yellow'}"><span>${label} contribution</span><strong>${v>0?'+':''}${money(v)}</strong></div>`).join('');
$('signals').innerHTML=[['Promotion share',`${d.promo}% vs. 25%`,`${d.promo-25} percentage points. Compare promoted and non-promoted weeks; the price metric already includes promotions.`],['On-shelf availability',`${d.stock}% vs. 97%`,`${d.stock-97} percentage points. Check whether missing stock is concentrated in high-volume SKUs.`],['Price vs. competitor',`${money(d.price)} vs. ${money(d.competitor)}`,`Sample matched-pack competitor price is flat. Our premium is ${((d.price/d.competitor-1)*100).toFixed(1)}%. Verify price per pound.`]].map(([a,b,t])=>`<div class="signal"><small>! Hypothesis to investigate</small><strong>${a}</strong><strong>${b}</strong><p>${t}</p></div>`).join('');
$('news-angle').textContent=d.price>20?'Our sample price rose while promotion share fell. Walmart’s emphasis on value makes a competitive price audit worth prioritizing. It does not prove inflation or a rollback caused the unit decline.':'Walmart’s value strategy is useful background, but this sample has no price change. Prioritize store coverage and availability before using a pricing story to explain the result.';
let actions=dist&&declining?[
['Audit the missing stores','Identify delisted, out-of-stock, and zero-sales stores. Confirm which losses are recoverable before changing price.','Sales + supply · 48 hours · Recover authorized selling stores'],
['Protect velocity in retained stores','Validate the +2% velocity signal in a constant-store, constant-SKU cohort. Separate true demand from store mix.','Category analytics · This week · Comparable-store units'],
['Rebuild the forecast','Model recovery using confirmed store reinstatements and current velocity. Do not assume every lost store returns.','Demand planning · Next review · Forecast error']
]:key==='recovery'?[
['Verify the recovery holds','Check that higher velocity and availability persist across comparable stores and SKUs for four weeks.','Category analytics · Weekly · Sustained unit growth'],
['Close the remaining store gap','Investigate the 50-store shortfall against the prior-year baseline and confirm replenishment capacity.','Sales + supply · This week · Selling store coverage'],
['Test before scaling spend','Use a matched-store holdout for any incremental marketing. Track incremental units and margin, not attributed sales alone.','Marketing · Four-week test · Incremental gross profit']
]:[
['Restore availability first','Find high-volume SKUs behind the 4-point availability drop. Confirm receipts and shelf execution before funding more demand.','Supply + retailer team · 48 hours · On-shelf availability'],
['Test the value gap','Audit matched-pack price per pound and promo calendars. Test a targeted offer in comparable, in-stock stores with a holdout; monitor margin.','Revenue growth + sales · Two weeks · Incremental units & gross margin'],
['Separate promotion from underlying demand','Compare like-for-like stores and SKUs across promoted and base weeks, controlling for availability. Test whether velocity remains weak at comparable prices.','Category analytics · This week · Base velocity and promo lift']
];
$('actions').innerHTML=actions.map(([h,p,n],i)=>`<article class="action"><span class="num">0${i+1}</span><div><h3>${h}</h3><p>${p}</p><small>${n}</small></div></article>`).join('');}
$('scenario').addEventListener('change',()=>{selected='sales';render($('scenario').value);$('status').textContent='Scenario updated. Run to review the analysis sequence.';document.querySelectorAll('#steps li').forEach(x=>x.className='');});
$('run').addEventListener('click',async()=>{const btn=$('run');btn.disabled=true;$('scenario').disabled=true;const steps=[...document.querySelectorAll('#steps li')];steps.forEach(x=>x.className='');for(let i=0;i<steps.length;i++){steps[i].className='active';$('status').textContent=steps[i].textContent+'…';if(i===0&&Object.values(samples[current]).some(v=>!Number.isFinite(v)||v<0)){ $('status').textContent='Invalid sample. Reload to restore data.';btn.disabled=false;$('scenario').disabled=false;return;}if(i===1)calculate(samples[current]);if(i===6)render(current);await new Promise(r=>setTimeout(r,matchMedia('(prefers-reduced-motion: reduce)').matches?0:260));steps[i].className='done';}$('status').textContent='Investigation complete. Inspect a metric or review the action plan.';btn.disabled=false;$('scenario').disabled=false;btn.textContent='Run again ↗';});render('base');}
