'use strict';
function tvSample(pattern){return Array.from({length:46},(_,i)=>{const t=i-15,expected=100+Math.round(5*Math.sin(i/6)),noise=[-3,2,-1,4,-2,1,0][i%7];const first=t>=0?Math.round(60*Math.exp(-t/5)):0;const second=t>=4?Math.round(45*Math.exp(-(t-4)/5)):0;return{t,expected,observed:expected+noise+(pattern==='quiet'?0:first)+(pattern==='overlap'?second:0)};});}
function tvSummary(rows,window){const selected=rows.filter(x=>x.t>=0&&x.t<window),expected=selected.reduce((s,x)=>s+x.expected,0),observed=selected.reduce((s,x)=>s+x.observed,0);return{selected,expected,observed,excess:observed-expected,percent:100*(observed-expected)/expected};}
if(typeof module!=='undefined')module.exports={tvSample,tvSummary};
if(typeof document!=='undefined'){
const $=id=>document.getElementById(id);
function updateTV(){const pattern=$('tv-pattern').value,win=Number($('tv-window').value),rows=tvSample(pattern),s=tvSummary(rows,win),x=t=>65+(t+15)*18,y=v=>255-(v-70)*1.65,path=k=>rows.map((r,i)=>(i?'L':'M')+x(r.t)+','+y(r[k])).join(' ');let grid=[80,100,120,140,160,180].map(n=>`<line x1="65" y1="${y(n)}" x2="875" y2="${y(n)}" stroke="#e3eaf1"/><text x="52" y="${y(n)+4}" text-anchor="end">${n}</text>`).join('');let ticks=[-15,-10,-5,0,5,10,15,20,25,30].map(n=>`<text x="${x(n)}" y="278" text-anchor="middle">${n}</text>`).join('');$('tv-chart').innerHTML=`<title id="chart-title">Synthetic web response: ${pattern}, ${win}-minute window</title><desc id="chart-desc">Observed sessions compared with expected baseline. ${s.excess} net excess sessions, ${s.percent.toFixed(1)} percent above baseline in the selected window.</desc><g font-family="Arial,sans-serif" font-size="13" fill="#526b80"><rect x="${x(0)}" y="35" width="${win*18}" height="220" fill="#fff3b8"/>${grid}${ticks}<text x="65" y="22">Sessions / minute</text><text x="470" y="303" text-anchor="middle">Minutes relative to first airing</text><path d="${path('expected')}" stroke="#71849a" stroke-width="2" stroke-dasharray="6 5" fill="none"/><path d="${path('observed')}" stroke="#0067b9" stroke-width="3" fill="none"/><line x1="${x(0)}" y1="35" x2="${x(0)}" y2="255" stroke="#003b71" stroke-dasharray="3 3"/><text x="${x(0)-8}" y="46" text-anchor="end">Spot A</text>${pattern==='overlap'?`<line x1="${x(4)}" y1="35" x2="${x(4)}" y2="255" stroke="#aa5b16" stroke-dasharray="3 3"/><text x="${x(4)+8}" y="46">Spot B</text>`:''}</g>`;
$('tv-kpis').innerHTML=[['Observed sessions',s.observed.toLocaleString()],['Net excess sessions',(s.excess>0?'+':'')+s.excess],['Above modeled baseline',s.percent.toFixed(1)+'%']].map(([label,value])=>`<div><span>${label}</span><strong>${value}</strong></div>`).join('');$('tv-readout').textContent=pattern==='overlap'?`Two candidate spots overlap within this ${win}-minute window. The ${s.excess} net excess sessions cannot all be credited to each spot. An allocation model or different evidence is needed to separate their contributions.`:pattern==='quiet'?`The ${win}-minute window contains ${s.excess} net excess sessions. This sample fluctuates around its baseline. There is no clear visible response; a percentage alone is not a significance test.`:`This ${win}-minute window contains ${s.excess} sessions above the supplied baseline (${s.percent.toFixed(1)}%). The pattern is consistent with an immediate response. It does not establish how many sessions the ad caused.`;$('tv-data').innerHTML=s.selected.map(r=>`<tr><td>${r.t}</td><td>${r.observed}</td><td>${r.expected}</td><td>${r.observed-r.expected}</td></tr>`).join('');}
$('tv-window').addEventListener('change',updateTV);$('tv-pattern').addEventListener('change',updateTV);updateTV();}
